### ISSUE TITLE
Window Watcher Not Working on M1 Monterey

### ISSUE THREAD

**Issue by vishalkrv** [ActivityWatch/aw-watcher-window#66] opened 2022-05-31 17:00 UTC
No Application or windows have been logged post installation. 

Activity Watcher Version: `v0.12.0b2`

Python Information:
```
  Version:	3.8.2
  Obtained from:	Apple
  Last Modified:	30/04/21, 9:54 PM
  Kind:	Universal

```
System Information:
  ```
  Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Chip:	                Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Version:	macOS 12.4 (21F79)
  Kernel Version:	Darwin 21.5.0
```
Log:
```
2022-05-31 22:19:46 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:75)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 72, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 55, in get_current_window
  File "aw_watcher_window/lib.py", line 27, in get_current_window_macos
  File "aw_watcher_window/macos_jxa.py", line 64, in getInfo
Exception: jxa error: Error: Error: An error occurred.
```

**Comment by ErikBjare** [comment] 2022-06-02 14:34
Duplicate of https://github.com/ActivityWatch/aw-watcher-window/issues/60

Closing

**Closed by ErikBjare** 2022-06-02 14:34 UTC
